name: flutter_web_firebase
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  shared_preferences: ^2.0.3
  google_sign_in: ^5.0.0
  flutter_bloc: ^6.1.3
  equatable: ^1.2.5
  font_awesome_flutter: ^8.11.0
  simple_animations: ^3.0.1
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  build_test: ^1.3.0
  build_web_compilers: ^2.12.0

flutter:
  uses-material-design: true

  assets:
    - lib/resources/images/
